project:
  type: website
  output-dir: _site

website:
  title: "Conservation Biology – GIS Tutorials"
  sidebar:
    style: docked
    search: true
    contents:

      - section: "1. Einführung"
        contents:
          - index.qmd

      - section: "2. Lecture"
        contents:
          - lecture1.qmd
          - lecture2.qmd

      - section: "3. QGIS"
        contents:
          - qgis_tutorial.qmd

      - section: "4. R Spatial"
        contents:
          - r_spatial_tutorial.qmd
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    highlight-style: github

execute:
  echo: true
  warning: false
  message: false
