project:
  type: website
  output-dir: _site

website:
  title: "Conservation Biology – Biotope Mapping and Data Processing"

  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - qfield_tutorial.qmd
      - section: "3. 💻 QGIS Tutorial"
        contents:
          - qgis_tutorial.qmd
          - qis_workflow.qmd
      - r_spatial_tutorial.qmd

      - section: "📚 Additional Resources"
        contents:
          - cheat_sheet.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    highlight-style: github

execute:
  echo: true
  warning: false
  message: false